### ISSUE TITLE
Suggestion (Please DO)

### ISSUE THREAD

**Issue by amosayomide05** [Eltik/Anify-API#1]
Please can you release this as a npm package so we can also use it easily

**Comment by Eltik** [comment]
Hey thanks for the suggestion. Sure I can make this an NPM package. This is meant to be a web server though. What would you want specifically for the package? Like searching, getting source links, etc.?

**Comment by Eltik** [comment]
https://www.npmjs.com/package/anify.js
I added it. If there is a specific feature you want let me know. You can import the package via:
```bash
npm i anify.js
```
And then in your project:
```javascript
// ES6
import Anify from "anify.js"

// CommonJS
const Anify = require("anify.js").default;

let anify = new Anify();
anify.search("my hero academia season 6").then(console.log)
```

**Comment by amosayomide05** [comment]
What about getting source links?

**Comment by Eltik** [comment]
> What about getting source links?

Yep that's added as well.
```javascript
const Anify = require("anify.js").default;
let anify = new Anify();
// Parameters are [AniList ID, provider name, watch ID]
anify.getSources("21", "Zoro", "/watch/one-piece-100").then(console.log)
```

**Comment by amosayomide05** [comment]
![image](https://user-images.githubusercontent.com/62471060/216902146-6d02e56e-fa13-4e73-bbcd-fc56737c4a81.png)

**Comment by Eltik** [comment]
> ![image](https://user-images.githubusercontent.com/62471060/216902146-6d02e56e-fa13-4e73-bbcd-fc56737c4a81.png)

Oops I messed up Kitsu. I fixed it! Just an FYI the library uses PostgresSQL so you'll need to setup a quick SQL server. I switched because it's faster. I also added an options constructor parameter so you can configure how everything works. For example:
```javascript
const Core = require("anify.js").default; // Switched the name from Anify -> Core
const anify = new Core({ database_url: "postgresql://postgres:password@localhost:3306", debug: true });
```
